### ISSUE TITLE
Add more logic to `frobenius` and `inertia` functions to make them function without roots sometimes

### ISSUE THREAD

**Issue by alexjbest** [alexjbest/cluster-pictures#35]
E.g. at the moment we make use of the fact that the top cluster is fixed by any automorphism.
We could implement more checks to see if there is other information pinning down these actions combinatorially, e.g.
```
((**)(***))
```
must have trivial inertia/frobenius on all proper clusters due to size considerations.
or likewise for
```
((***)_1/3(***)_2/3)
```
due to depth considerations.

**Comment by rbommel** [comment]
Yeah, I think it makes sense to compute the automorphism group for clusters, an automorphisms being considered as the identity when it fixes all principal clusters. If it has only one element, then you know any Galois action is trivial, like you say.

**Comment by rbommel** [comment]
Commit 0e6ebd751bec6cb40d5b965f0acbe8be21f9025c can compute the automorphism group.
