### ISSUE TITLE
'EisensteinExtensionFieldCappedRelative_with_category' object has no attribute 'relative_discriminant'

### ISSUE THREAD

**Issue by rbommel** [alexjbest/cluster-pictures#37]
This error you get when trying to compute the conductor for the genus 2 curve 360.a.6480.1 at the prime 5.

**Comment by alexjbest** [comment]
Ah yes I forgot that 5 is not bigger than 2*2 + 1. Like you said before probably the best long term strategy is to wait for sage, butttt, hacking around it is fun so:
I added a couple of hacks that make this example work:
- Sage cant take discriminant (or discriminant exponent) of a local field it seems, so use the "fact" that this is 1 for unramified extensions
- Similarly for degree 2 ramified extensions use that this exponent is always 1.
This can be extended by looking at the Jones-Roberts database or by me learning about local fields lol (i.e. from https://www.lmfdb.org/LocalNumberField/?hst=List&n=3&p=3-&e=3&search_type=List we see that a degree 3 ramified extension of local fields has discriminant exponent 2 once p >= 5, so we could add a couple more special cases like this)

btw if you know references for these facts let me know!

**Comment by alexjbest** [comment]
closed by d1ccb3105fcaa75fc5c03a5df3c5a288f2f95687 as this example now works, but please open more issues if we hit NotImplementedError for the discriminant functions especially as it looks like I can add more workarounds

**Comment by rbommel** [comment]
Yeah, so I guess in the tame case, a ramified extension of degree e can be modelled as K < K(u^(1/e)) for a uniformiser e. So then it probably suffices to compute that discriminant. I suspect it is the wild case that will make your life hard.

**Comment by alexjbest** [comment]
Yes that makes sense, I'll try and work out the actual formula then xD
