### ISSUE TITLE
Slow automorphisms

### ISSUE THREAD

**Issue by rbommel** [alexjbest/cluster-pictures#45]
A colleague reported to me that there is a problem when computing the Tamagawa number of the following curve:
```sage: p = 7
sage: x = polygen(Qp(p,150))
sage: H = HyperellipticCurve(x^(12) + 36*x^(11) + 534*x^(10) + 4094*x^9 + 17667*x^8 + 44018*x^7 + 61093*x^6 + 44018*x^5 + 17667*x^4 + 4094*x^3 + 534*x^2 + 36*x + 1)
sage: C = Cluster.from_curve(H)
sage: C.tamagawa_number()
```
After digging into this, it seems that the problem is caused by the computation of the combinatorial automorphism group in `inertia`. I think the problem would be solved in this case by first checking for the `_inertia` attribute before iterating over the full automorphism group. If you agree, I will change that. Maybe we should also print a warning if this clause is triggered.

**Comment by rbommel** [comment]
Oh oops, I thought I was making a pull request, but I actually immediately changed the main branch. Anyway, still let me know if you agree.

**Comment by alexjbest** [comment]
@rbommel This change looks good to me, what is p in that example? We should add it as a test, and I should also fix the CI

**Comment by rbommel** [comment]
Seven

**Comment by alexjbest** [comment]
Well now I'm super confused, did we talk about this before? I have this change locally already lol

**Comment by rbommel** [comment]
Maybe check if you are in sync with the Github branch?
